#This file is a template showing the layout of an experiment config file, and all
#hardware that the program knows about. When new pieces of hardware are added with
#new interfaces, they should be added to the list of "AvailableHardware." Their configuration
#information, if any, should then be added to HardwareConfig. the type indicators are used to
#make the GUI for editing the config file.

#This determines whether a GUI is shown at the program start to allow setting
#all the fields in this file. If ShowExperimentConfigGui is True, then the GUI
#will be initialized via this file, but will subsequently overwrite it.
ShowExperimentConfigGui: bool

#This section defines what pieces of hardware are physically available.
#In this template, all known pieces hardware elements or classes of elements
#are listed.
AvailableHardware:
  - Pulser_FPGA
  - 32ChannelPMT_FPGA
  - ConexMotion
  - APTMotion
  - VISAInstruments

#This section defines how different pieces of hardware are configured.
#It does not matter if the hardware is present or not, as this information is
#only used if the hardware is listed as available.
HardwareConfig:
  Pulser_FPGA:
    Type: OpalKellyFPGA
    SoftwareRole: Pulser
    Name: str
    Instrument: str
    BitFile: path
    UploadOnStartup: bool
  32ChannelPMT_FPGA:
    Type: OpalKellyFPGA
    SoftwareRole: 32ChannelPMT
    Name: str
    Instrument: str
    BitFile: path
    UploadOnStartup: bool
  DAC_FPGA:
    Type: OpalKellyFPGA
    SoftwareRole: Voltages
    Name: str
    Instrument: str
    BitFile: path
    UploadOnStartup: bool
  Chase_AWG:
    Type: ChaseAWG
    SoftwareRole: AWG
    Name: str
    Instrument: str
    DLL: str

#This section defines how the software is configured. If an element is missing,
#that software element is disabled.
#
SoftwareConfig:
  Pulser: Pulser_FPGA
  Voltages: DAC_FPGA
  AWG: Chase_AWG
  GateSequencesAvailable: True
  TimestampingAvailable: True

#This section defines the settings to use to connect to the database.
#Yes, the password is plain text. Don't use one you care deeply about.
DatabaseConnection:
  user: str
  password: str
  database: str
  host: str
  port: int
  echo: bool