#This file is a template used in creating the GUI for editing the experiment configuration. It documents all hardware and software that the program knows about. When new pieces of hardware (or configurable software) are added with new interfaces, they should be added here, together with their configuration information, if any.

#The GUI uses the "fields" dictionary to generate the configuration interface. Each field must be specified as a type. Known types are: role, path, str, int, float, bool

#"software" is a dictionary of particular pieces of functionality available in the software, which have their own configuration information. For example, "Voltages" is a software feature, which must be configured by specifying its corresponding hardware. Hardware is a field of type "role," which means that the hardware can be set to any piece of hardware with role=Voltages.
software:
  &P Pulser:
    fields:
      hardware: role
  &V Voltages:
    fields:
      hardware: role
  &A AWG:
    fields:
      hardware: role
  Gate Sequences:
  Timestamps:

#"hardware" are pieces of hardware together with configuration information. If a hardware has a role, it can be selected under the corresponding software's "hardware" field.
hardware:
  "FPGA: Pulser":
    role: *P
    fields:
      deviceIdentifier: str
      instrument: str
      bitFile: path
      uploadOnStartup: bool
  "FPGA: 32 Channel PMT":
    fields:
      deviceIdentifier: str
      instrument: str
      bitFile: path
      uploadOnStartup: bool
  "FPGA: DAC":
    role: *V
    fields:
      deviceIdentifier: str
      instrument: str
      bitFile: path
      uploadOnStartup: bool
  NI Chassis:
    role: *V
    fields:
      name: str
      configFile: path
  Chase AWG:
    role: *A
    fields:
      name: str
      instrument: str
      DLL: str
  Conex Motion:
  APT Motion:
  VISA: