#This is a commented example showing what an experiment config file looks like.

#This determines whether a GUI is shown at the program start to allow setting
#all the fields in this file. If ShowExperimentConfigGui is True, then the GUI
#will be initialized via the config file, but will subsequently overwrite it.
ShowExperimentConfigGui: False

#This section defines how different pieces of hardware are configured.
#It does not matter if the hardware is present or not, as this information is
#only used if the hardware is listed as available.
HardwareConfig:
  Pulser_FPGA:
    Type: OpalKellyFPGA
    SoftwareRole: Pulser
    Name: ChipLabPulseProgrammer
    Instrument: Opal Kelly XEM6010
    BitFile: C:\Users\jmizrahi\IonControl\FPGA_Ions\IonControl-firmware-UMD.bit
    UploadOnStartup: False
  32ChannelPMT_FPGA:
    Type: OpalKellyFPGA
    Name: 32PMTFPGA
    Instrument: Opal Kelly XEM6010
    BitFile: C:\Users\jmizrahi\IonControl\FPGA_Ions\mybitfile.bit
    UploadOnStartup: False
  DAC_FPGA:
    Type: OpalKellyFPGA
    SoftwareRole: Voltages
    Name: DACFPGA
    Instrument: Opal Kelly XEM6010
    BitFile: C:\Users\jmizrahi\IonControl\FPGA_Ions\mybitfile.bit
    UploadOnStartup: False
  Chase_AWG:
    Type: ChaseAWG
    SoftwareRole: AWG
    Name: Chase DA12000 AWG
    Instrument: Chase DA12000 AWG
    DLL: DA12000_DLL64.dll

#This section defines how the software is configured.
SoftwareRoles:
  Pulser: Pulser_FPGA
  Voltages: DAC_FPGA
  AWG: Chase_AWG
  
SoftwareFeatures:
  GateSequencesAvailable: True
  TimestampingAvailable: True

#This section defines what pieces of hardware are physically available
AvailableHardware:
  - Pulser_FPGA
  - 32ChannelPMT_FPGA
  - ConexMotion
  - APTMotion
  - VISAInstruments

#This section defines the settings to use to connect to the database.
#Yes, the password is plain text. Don't use one you care deeply about.
DatabaseConnection:
  user: python
  password: mydbpassword
  database: ioncontrol
  host: localhost
  port: 5432
  echo: False